import type { Metadata } from "next";
// import {ClientInit} from "@/components/ClientInit";
// import { ClientInit } from '../components/ClientInit';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <ClientInit />   🔥 100% client-run guaranteed */}
        {children}
      </body>
    </html>
  );
}
